#!/usr/bin/env node
// sessions.json is the source of truth. sessions.js is generated and committed, and the
// page loads it as a plain global. No fetch, no JSON parsing at runtime, no server.
// Never hand-edit sessions.js.
//
//   node build.mjs

import fs from "node:fs";
import path from "node:path";

const HERE = path.dirname(new URL(import.meta.url).pathname);
const SRC = path.join(HERE, "sessions.json");
const OUT = path.join(HERE, "sessions.js");

const data = JSON.parse(fs.readFileSync(SRC, "utf8"));

if (!Array.isArray(data.sessions)) throw new Error("sessions.json needs a sessions array");
const seen = new Set();
for (const s of data.sessions) {
  if (typeof s.n !== "number") throw new Error(`session missing a number: ${JSON.stringify(s).slice(0, 80)}`);
  if (seen.has(s.n)) throw new Error(`two sessions both numbered ${s.n}`);
  seen.add(s.n);
  if (!Array.isArray(s.essays)) throw new Error(`session ${s.n} has no essays array`);
}
data.sessions.sort((a, b) => a.n - b.n);

fs.writeFileSync(OUT,
  "/* generated by build.mjs from sessions.json. Do not edit. */\n" +
  "window.SESSIONS=" + JSON.stringify(data) + ";\n");

const essays = data.sessions.reduce((a, s) => a + s.essays.length, 0);
console.log(`sessions.js  ${data.sessions.length} session(s), ${essays} essay(s)`);
